[build-system]
# These are the assumed default build requirements from pip:
# https://pip.pypa.io/en/stable/reference/pip/#pep-517-and-518-support
# DEBUG: FORCE DEBULD
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"