# Github action that makes sure that all the version tags are up to date when
# A new version is released.
# NOTE: Runs when a new version is released (not published).
name: MLC bump CI
on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    types:
      - labeled
jobs:
  release-tag:
    if: github.event.action != 'labeled'
    runs-on: ubuntu-latest
    steps:
      # NOTE: Makes sure the new version also contains the right major and minor tags.
      - uses: actions/checkout@v2
      # Bump version on merging Pull Requests with specific labels.
      # (bump:major,bump:minor,bump:patch)
      - id: bumpr
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: haya14busa/action-bumpr@v1
      # Update corresponding major and minor tag.
      # e.g. Update v1 and v1.2 when releasing v1.2.3
      - uses: haya14busa/action-update-semver@v1
        if: "!steps.bumpr.outputs.skip"
        with:
          tag: ${{ steps.bumpr.outputs.next_version }}
  release-check:
    # NOTE: Used to check if the bump:version label is working
    if: github.event.action == 'labeled'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Post bumpr status comment
        uses: haya14busa/action-bumpr@v1
