# Github action that checks if the documentation still builds
# NOTE: Runs when changes were made to the docs folder. This is used to check if the
# documentation still builds
name: Docs build check CI
on:
  pull_request:
    paths:
      - "docs/**"
    branches:
      - main
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GA_SUB }}
          fetch-depth: 0
      - name: Install system dependencies
        run: sudo apt update; sudo apt install libopenmpi-dev
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Cache python environment
        uses: actions/cache@v2
        id: cache-python-env
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('setup.cfg') }}-${{ hashFiles('pyproject.toml') }}-docs
      - name: Update pip
        if: steps.cache-python-env.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
      - name: Install the mlc package with its dependencies
        if: steps.cache-python-env.outputs.cache-hit != 'true'
        run: |
          pip install -e .[docs]
      - name: Lints sphinx documentation and posts comments
        uses: rickstaa/sphinx-action-composite@v1.0.0
        with:
          docs-folder: "./docs"
      - name: Upload build documentation
        uses: actions/upload-artifact@v2
        with:
          name: html-docs
          path: docs/build/html/
