# # Github action that checks if the documentation still builds
# name: Docs build CI
# on:
#   push:
#     paths:
#       - "docs/**"
#     branches:
#       - main
#   pull_request:
#     paths:
#       - "docs/**"
#     branches:
#       - main
# jobs:
#   build-docs:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout mlc repository
#         uses: actions/checkout@v2
#         with:
#           submodules: recursive
#           token: ${{ secrets.GA_SUB }}
#       - name: Install system dependencies
#         run: sudo apt-get install libopenmpi-dev
#       - name: Set up Python environment
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3.7
#       - name: Cache python environment
#         uses: actions/cache@v2
#         id: cache-python-env
#         with:
#           path: ${{ env.pythonLocation }}
#           key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('setup.cfg') }}-${{ hashFiles('pyproject.toml') }}
#       - name: Update pip
#         run: |
#           python -m pip install --upgrade pip
#       - name: Install the mlc package with its dependencies
#         if: steps.cache-python-env.outputs.cache-hit != 'true'
#         run: |
#             pip install -e .[docs]
#       - name: Check if documentation builds
#         uses: ammaraskar/sphinx-action@master
#         with:
#           docs-folder: "docs/"
#       - name: Upload build documentation
#         uses: actions/upload-artifact@v2
#         with:
#           name: DocumentationHTML
#           path: docs/_build/html/
