name: Docs
on: 
  push:
    tags:
      - v*.*.*
    paths:
      - 'docs/**'
  workflow_dispatch:
permissions:
    contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: 
          python-version: 3.8
          cache: 'pip'
          cache-dependency-path: pyproject.toml
      - name: Install system dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libopenmpi-dev
          version: 1.0
      - name: Install dependencies
        run: |
          pip install .[docs]
      - name: Sphinx build
        run: |
          sphinx-build docs/source docs/build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/
          force_orphan: true
