# Main push/Pull request CI config file
# Note: For local testing with https://github.com/nektos/act use the
# `sudo act -P ubuntu-18.04=nektos/act-environments-ubuntu:18.04` command.
name: MLC pull CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: local-fix
        run: |
          # Hack to get setup-python to work on act
          # (see https://github.com/nektos/act/issues/251)
          if [ ! -f "/etc/lsb-release" ] ; then
            echo "DISTRIB_RELEASE=18.04" > /etc/lsb-release
          fi
      - name: install-deps
        run: sudo apt-get install libopenmpi-dev
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: pip-cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements_dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: install-pip-deps
        run: pip3 install -r requirements.txt

  python-lint:
    name: python-flake8 (Runner)
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run flake8 on your PR - with annotations!
        uses: tayfun/flake8-your-pr@1.0.1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  # python-format:
  #   name: python-format
  #   needs: build
  #   runs-on: ubuntu-18.04
  #   steps:
  #     # - uses: actions/checkout@v2
  #     - name: python-black
  #       uses: lgeiger/black-action@v1.0.1
  #       with:
  #         args: ". --check"

  # python-tests:
  #   name: python-tests
  #   needs: build
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: python-tests
  #       uses: cclauss/GitHub-Action-for-pytest@0.5.0
  #       with:
  #         args: pytest

  # markdown-lint:
  #   name: runner / markdown-lint
  #   needs: build
  #   runs-on: ubuntu-18.04
  #   steps:
  #     # - uses: actions/checkout@v1
  #     - name: remark-lint
  #       uses: prologic/action-remark-lint@v0.0.5
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         reporter: github-pr-check # Change reporter. (Only `github-pr-check` is supported at the moment).
