# Main push/Pull request CI config file
# Note: For local testing with https://github.com/nektos/act use the
# `sudo act -P ubuntu-18.04=nektos/act-environments-ubuntu:18.04` command.
name: MLC pull CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch

  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: runner / build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: local-fix
        run: |
          # Hack to get setup-python to work on act
          # (see https://github.com/nektos/act/issues/251)
          if [ ! -f "/etc/lsb-release" ] ; then
            echo "DISTRIB_RELEASE=18.04" > /etc/lsb-release
          fi
      - name: install-deps
        run: sudo apt-get install libopenmpi-dev
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: pip-cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements_dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: install-pip-deps
        run: pip3 install -r ci_requirements.txt

  python-lint:
    name: runner / python-lint
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: python-lint
        uses: tayfun/flake8-your-pr@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  black-format:
    name: runner / black-format
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        # with:
        #   fetch-depth: 0
      - name: python-black
        uses: lgeiger/black-action@v1.0.1
        with:
          args: "./machine_learning_control --check"

  python_tests:
    name: runner / python-tests
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: python-tests
        uses: cclauss/GitHub-Action-for-pytest@0.5.0
        with:
          args: pytest

  remark-lint:
    name: runner / remark-lint
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - name: remark-lint
        uses: prologic/action-remark-lint@v0.0.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check # Change reporter. (Only `github-pr-check` is supported at the moment).
