# Main push/Pull request CI config file
# Note: For local testing with https://github.com/nektos/act use the
# `sudo act -P ubuntu-18.04=nektos/act-environments-ubuntu:18.04` command.
name: MLC pull CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 2
      - name: Install system dependencies
        run: sudo apt-get install libopenmpi-dev
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Create pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements_dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install pip dependencies
        run: pip3 install -r requirements.txt
      - name: Install mlc pip package
        run: pip3 install .

  python-lint:
    name: python-flake8 (Runner)
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 2
      - name: Run flake8 on your PR - with annotations!
        # uses: tayfun/flake8-your-pr@1.0.1 # NOTE: Contains a bug
        uses: valentijnscholten/flake8-your-pr@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  python-format:
    # Currently has a bug (see https://github.com/lgeiger/black-action/issues/11).
    name: python-black
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 2
      - name: python-black
        uses: lgeiger/black-action@v1.0.1

  python-tests:
    name: python-tests
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: python-tests
        uses: cclauss/GitHub-Action-for-pytest@0.5.0
        with:
          args: pytest ./machine_learning_control

  markdown-lint:
    # Currently has a bug (see https://github.com/prologic/action-remark-lint/pull/4).
    name: markdown-lint (Runner)
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 2
      - name: remark-lint
        # uses: prologic/action-remark-lint@v0.0.5
        uses: rickstaa/action-remark-lint@fix_reviewdog_exit_code_bug
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check # Change reporter. (Only `github-pr-check` is supported at the moment).
          level: warning