# name: Linux CI

# on:
#   push:
#   pull_request:

# jobs:
#   test-check:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         python-version: [3.6, 3.7, 3.8, 3.9, pypy3]
#     name: Linux CI (github-check)
#     steps:
#       - name: Check out source repository
#         uses: actions/checkout@v2
#       - name: Set up Python ${{ matrix.python-version }} environment
#         uses: actions/setup-python@v1
#         with:
#           python-version: ${{ matrix.python-version }}
#       - name: Python environment report
#         run: python -c "import sys; print(sys.version)"
#       - name: Run ${{ matrix.python-version }} platform tests (default)
#         uses: reviewdog/action-flake8@master
#         with:
#           path: "tests/test-default.py" # have to restrict because there are other tests with flake8 fails
#       - name: Run ${{ matrix.python-version }} platform tests (with args)
#         uses: reviewdog/action-flake8@master
#         with:
#           update_pip: "true"
#           ignore: "F401"
#           exclude: "tests/test.py"
#           max_line_length: "100"
#           args: "--quiet"
#           path: "tests/test-args.py"
#           flake8_version: "master"
#           github_token: ${{ secrets.github_token }}
#           reporter: github-check
#           level: info

#   test-pr-check:
#     if: github.event_name == 'pull_request'
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         python-version: [3.6, 3.7, 3.8, 3.9, pypy3]
#     name: Linux CI (github-pr-check)
#     steps:
#       - name: Check out source repository
#         uses: actions/checkout@v2
#       - name: Set up Python ${{ matrix.python-version }} environment
#         uses: actions/setup-python@v1
#         with:
#           python-version: ${{ matrix.python-version }}
#       - name: Python environment report
#         run: python -c "import sys; print(sys.version)"
#       - name: Run ${{ matrix.python-version }} platform tests (default)
#         uses: reviewdog/action-flake8@master
#         with:
#           path: "tests/test-default.py" # have to restrict because there are other tests with flake8 fails
#       - name: Run ${{ matrix.python-version }} platform tests (with args)
#         uses: reviewdog/action-flake8@master
#         with:
#           update_pip: "true"
#           ignore: "F401"
#           exclude: "tests/test.py"
#           max_line_length: "100"
#           args: "--quiet"
#           path: "tests/test-args.py"
#           flake8_version: "master"
#           github_token: ${{ secrets.github_token }}
#           reporter: github-pr-check
#           level: warning
