name: Push CI
on: [push]

jobs:
  test_push:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install apt dependencies
        run: sudo apt-get install libopenmpi-dev

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # FIXME: CACHE DOES NOT WORK!
      - name: Cache pip
        uses: actions/cache@v1
          id: pip_packages_cache
          with:
            path: .cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements_dev.txt') }}
            restore-keys: |
              ${{ runner.os }}-pip-
              ${{ runner.os }}-

      - name: Install dependencies
        run: pip install -r requirements_dev.txt

      - name: Run Pylint
        run: python lint.py --path ./machine_learning_control --threshold 2

      # - name: Code Quality
      #   run: black ./machine_learning_control --check

      # - name: Test with pytest
      #   run: pytest ./machine_learning_control -vn 2
