# Github action that build the documentation when you publish a new version.
# NOTE: Runs when a new version is published.
name: Docs CI
on:
  push:
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: install dvisvgm
        run: apt update; apt search dvisvgm
      - name: test dvisvgm
        run: dvisvgm
