on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-event:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mlc repository
        uses: actions/checkout@v2
      - name: Get latest tag
        id: get-latest-tag
        run: |
          LATEST_TAG=$(git tag | grep v* | sort --version-sort --reverse | head -n1)
          echo $LATEST_TAG
          LATEST_TAG="test"
          echo "LATEST_TAG=${LATEST_TAG}" >> $GITHUB_ENV
      - name: Cat event file
        run: |
          echo ":rocket: Deploys documentation $LATEST_TAG - ${{ github.event.head_commit.id }}"