on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-event:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest tag
        id: get-latest-tag
        run: |
          echo "LATEST_TAG=$(git tag | grep v* | sort --version-sort --reverse | head -n1)" >> $GITHUB_ENV
      - name: Cat event file
        run: |
          echo ":rocket: Deploys documentation $LATEST_TAG - ${{ github.event.head_commit.id }}"