on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-event:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@master"
      - name: Cat event file
        run: |
          echo ":rocket: Deploys documentation ${{ steps.previoustag.outputs.tag }} - ${{ github.event.head_commit.id }}"