on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-event:
    runs-on: ubuntu-latest
    steps:
      - name: Cat event file
        run: |
          echo ":rocket: Deploys documentation ${{ github.event.head_commit.id }}"