# Action used to update the major and minor tags automatically.
name: Update semver CI
on:
  push:
    branches-ignore:
      - "**"
    tags:
      - "v*.*.*"

jobs:
  update-semver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haya14busa/action-update-semver@v1